name: Docker Context Action

on:
  push:
    branches: [ "master" ]

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout master
      uses: actions/checkout@main

    - uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

    - name: Build container image
      run: docker build -t ${{ secrets.REGISTRY_NAME }}/docker-context-action:$(echo $GITHUB_SHA | head -c7) .

    - name: Log in to DigitalOcean Container Registry with short-lived credentials
      run: doctl registry login --expiry-seconds 1200

    - name: Push image to DigitalOcean Container Registry
      run: docker push ${{ secrets.REGISTRY_NAME }}/docker-context-action:$(echo $GITHUB_SHA | head -c7)
